### ISSUE TITLE
Problem Running SEQPower

### ISSUE THREAD

**Issue by rahapazoki** [gaow/SEQPower#1]
After installing Spower, I received the error below when I tried to run the program.  Does anyone have any idea about the problem?

 Traceback (most recent call last):
   File "/hpc/local/CentOS6/hers_en/anaconda/bin/spower", line 10, in <module>
     from spower.opts import CalculatorOpt
    File "/hpc/local/CentOS6/hers_en/anaconda/lib/python2.7/site-packages/spower/opts.py", line 13, in <module>
     from spower.calculator.manager import Executor, showTests, showFields
    File "/hpc/local/CentOS6/hers_en/anaconda/lib/python2.7/site-packages/spower/calculator/manager.py", line 20, in <module>
      from spower.calculator.algorithms import *
    File "/hpc/local/CentOS6/hers_en/anaconda/lib/python2.7/site-packages/spower/calculator/algorithms.py", line 14, in <module>
     from cstatgen.gsl_py2 import *
 ImportError: No module named cstatgen.gsl_py2

**Comment by gaow** [comment]
Hey Raha,

Would you please try to install ["cstatgen" library](http://www.bioinformatics.org/spower/upload/cstatgen.tar.gz) manually and see? SEQPower should automatically download and install it if [all dependencies](http://www.bioinformatics.org/spower/installation) are met. Clearly it failed in your case so running cstatgen installation manually (by [the same instructions](http://www.bioinformatics.org/spower/installation) as SEQPower installation) should help you see where the problem is and fix it accordingly. It seems you are running it on an institutional HPC so the cstatgen auto-install may fail if the HPC does not have access to the Internet.

**Comment by gaow** [comment]
A note for Mac users: SEQPower no longer releases Mac binaries since version 1.0.1. Here is what it took to make it work on Mac OS 10.8 for source compiling cstatgen for SEQPower version 1.1.0:
1. Install XCode command line tool
2. install macport or homebrew
3. use macport or home-brew to install gcc-4.8
4. enable gcc-4.8 g++-4.8 as system default gcc compiler (verify by >> gcc --version)
5. build python2.7 from src locally (--prefix=/Users/usrname/...)
6. use locally built python to install cstatgen (>> /Users/usrname/.../bin/python2.7 setup.py install)
7. add PYTHONPATH to ~/.bash_profile (export PYTHONPATH=/Users/usrname/.../lib/python2.7/site-packages:$PYTHONPATH)
8. see if anaconda/python can successfully load cstatgen (>> python -c "import cstatgen; help(cstatgen)")

**Comment by gaow** [comment]
Docker image for `SEQPower` and instruction to run `SEQPower` from docker has been updated [here](http://bioinformatics.org/spower/installation).
